# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pfeffernusse.models.base_model_ import Model
from pfeffernusse import util


class ISD200ReferenceHeight(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, minheight: float=None, maxheight: float=None):  # noqa: E501
        """ISD200ReferenceHeight - a model defined in Swagger

        :param minheight: The minheight of this ISD200ReferenceHeight.  # noqa: E501
        :type minheight: float
        :param maxheight: The maxheight of this ISD200ReferenceHeight.  # noqa: E501
        :type maxheight: float
        """
        self.swagger_types = {
            'minheight': float,
            'maxheight': float
        }

        self.attribute_map = {
            'minheight': 'minheight',
            'maxheight': 'maxheight'
        }

        self._minheight = minheight
        self._maxheight = maxheight

    @classmethod
    def from_dict(cls, dikt) -> 'ISD200ReferenceHeight':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ISD200_reference_height of this ISD200ReferenceHeight.  # noqa: E501
        :rtype: ISD200ReferenceHeight
        """
        return util.deserialize_model(dikt, cls)

    @property
    def minheight(self) -> float:
        """Gets the minheight of this ISD200ReferenceHeight.


        :return: The minheight of this ISD200ReferenceHeight.
        :rtype: float
        """
        return self._minheight

    @minheight.setter
    def minheight(self, minheight: float):
        """Sets the minheight of this ISD200ReferenceHeight.


        :param minheight: The minheight of this ISD200ReferenceHeight.
        :type minheight: float
        """
        if minheight is None:
            raise ValueError("Invalid value for `minheight`, must not be `None`")  # noqa: E501

        self._minheight = minheight

    @property
    def maxheight(self) -> float:
        """Gets the maxheight of this ISD200ReferenceHeight.


        :return: The maxheight of this ISD200ReferenceHeight.
        :rtype: float
        """
        return self._maxheight

    @maxheight.setter
    def maxheight(self, maxheight: float):
        """Sets the maxheight of this ISD200ReferenceHeight.


        :param maxheight: The maxheight of this ISD200ReferenceHeight.
        :type maxheight: float
        """
        if maxheight is None:
            raise ValueError("Invalid value for `maxheight`, must not be `None`")  # noqa: E501

        self._maxheight = maxheight
